#!/usr/bin/env python3
"""Generate CATALOG.md, an index of every workbook template in the repository.

For each category folder the catalog lists every ``*.workbook`` file with:

* a link to the file
* a title derived from the workbook itself (the first Markdown heading in an
  always-visible text step, then any heading, then the first sentence of the
  first text step, then the ``fromTemplateId`` the portal recorded, then the
  file name)
* the names of the workbook's top-level parameters, which is usually the
  quickest way to tell which resources a template expects
* the number of steps (items) in the workbook

Many files were exported from the portal with generic names such as
``Overview.workbook`` or ``Cluster (3).workbook``; the derived title is what
tells them apart, so keep this catalog regenerated whenever files change.

Usage:
    python scripts/build_catalog.py            # rewrite CATALOG.md
    python scripts/build_catalog.py --check    # exit 1 if CATALOG.md is stale
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "CATALOG.md"
MAX_TITLE = 90
MAX_PARAMS = 6

HEADING = re.compile(r"^\s{0,3}#{1,4}\s+(.+?)\s*#*\s*$", re.MULTILINE)
HTML_TAG = re.compile(r"<[^>]+>")
MD_LINK = re.compile(r"\[([^\]]*)\]\([^)]*\)")
MD_EMPHASIS = re.compile(r"(\*\*|__|\*|_|`)")


def clean_markdown(text: str) -> str:
    text = HTML_TAG.sub("", text)
    text = MD_LINK.sub(r"\1", text)
    text = MD_EMPHASIS.sub("", text)
    text = text.replace("|", "\\|")
    return " ".join(text.split())


def text_steps(items, include_conditional: bool):
    """Yield the Markdown of text steps in document order, descending into groups.

    Steps with ``conditionalVisibility`` are usually warnings ("select a
    workspace first"), so callers can skip them on a first pass.
    """
    for item in items or []:
        content = item.get("content") or {}
        conditional = bool(item.get("conditionalVisibility") or item.get("conditionalVisibilities"))
        if conditional and not include_conditional:
            continue
        if item.get("type") == 1:
            yield content.get("json") or ""
        elif item.get("type") == 12:  # group step
            yield from text_steps(content.get("items"), include_conditional)


def derive_title(items) -> str | None:
    """Best-effort title: an unconditional heading, then any heading, then the first sentence."""
    for include_conditional in (False, True):
        for markdown in text_steps(items, include_conditional):
            match = HEADING.search(markdown)
            if match:
                title = clean_markdown(match.group(1))
                if title:
                    return title
    for markdown in text_steps(items, True):
        plain = clean_markdown(markdown)
        if plain:
            sentence = re.split(r"(?<=[.!?])\s", plain, maxsplit=1)[0]
            return sentence
    return None


def top_level_parameters(items) -> list[str]:
    for item in items or []:
        if item.get("type") == 9:  # parameters step
            names = [p.get("name") for p in (item.get("content") or {}).get("parameters") or []]
            return [n for n in names if n]
    return []


def count_steps(items) -> int:
    total = 0
    for item in items or []:
        total += 1
        if item.get("type") == 12:
            total += count_steps((item.get("content") or {}).get("items"))
    return total


def describe(path: Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    items = data.get("items") or []
    title = derive_title(items) or data.get("fromTemplateId") or path.stem
    if len(title) > MAX_TITLE:
        title = title[: MAX_TITLE - 1].rstrip() + "…"
    params = top_level_parameters(items)
    shown = ", ".join(params[:MAX_PARAMS]) + (", …" if len(params) > MAX_PARAMS else "")
    return {"title": title, "params": shown or "—", "steps": count_steps(items)}


def render() -> str:
    categories = sorted(
        (d for d in ROOT.iterdir() if d.is_dir() and not d.name.startswith(".") and d.name != "scripts"),
        key=lambda d: d.name.lower(),
    )
    lines = [
        "# Workbook Catalog",
        "",
        "_Generated by `scripts/build_catalog.py`; do not edit by hand. "
        "Run `python scripts/build_catalog.py` after adding or changing workbooks._",
        "",
        "Titles are read from the first Markdown heading inside each workbook. "
        "Files that share a name with a numeric suffix (for example `Cluster (3).workbook`) "
        "are distinct templates that happened to be exported under the same name; "
        "use the title and parameters to tell them apart.",
        "",
        "## Categories",
        "",
        "| Category | Workbooks |",
        "| --- | ---: |",
    ]
    sections = []
    total = 0
    for category in categories:
        files = sorted(category.glob("*.workbook"), key=lambda p: p.name.lower())
        if not files:
            continue
        total += len(files)
        anchor = re.sub(r"[^a-z0-9 -]", "", category.name.lower()).replace(" ", "-")
        lines.append(f"| [{category.name}](#{anchor}) | {len(files)} |")
        section = [
            "",
            f"## {category.name}",
            "",
            "| Workbook | Title | Parameters | Steps |",
            "| --- | --- | --- | ---: |",
        ]
        for path in files:
            info = describe(path)
            href = quote(f"{category.name}/{path.name}")
            name = path.name.replace("|", "\\|")
            section.append(f"| [{name}]({href}) | {info['title']} | {info['params']} | {info['steps']} |")
        sections.append("\n".join(section))
    lines.append(f"| **Total** | **{total}** |")
    return "\n".join(lines) + "\n" + "\n".join(sections) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if CATALOG.md is out of date")
    args = parser.parse_args(argv)

    content = render()
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != content:
            print("CATALOG.md is out of date; run: python scripts/build_catalog.py")
            return 1
        print("CATALOG.md is up to date")
        return 0

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
